### ISSUE TITLE
Help using

### ISSUE THREAD

**Issue by GabrielPetrov** [Niki-Sal/MyExpressApp#1]
How exactly do I run/use this tool?

**Comment by GabrielPetrov** [comment]
After i click enter sea creature app i get "TypeError: C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\views\fish\allFishes.ejs:10
    8|           <a id="fish-name" href="/fishes/<%= fish[i]['Species Name'] %>"><%= fish[i]['Species Name'] %></a>

    9|         

 >> 10|           <img style = "max-width: 200px; height: auto" src="<%= fish[i]['Species Illustration Photo']['src'] %>" alt="fish image">

    11|         

    12|           <form method="POST" action="fishes/favorite/<%= fish[i]['Species Name'] %>/<%= fish[i]['Harvest Type'] %>">

    13|             <button class="btn btn-primary" type="submit">Add to Favorite</button>


Cannot read properties of undefined (reading 'src')
    at eval ("C:\\Users\\Fifth\\Documents\\Programming\\FishWatch\\FishWatch\\views\\fish\\allFishes.ejs":20:63)
    at allFishes (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\ejs\lib\ejs.js:703:17)
    at tryHandleCache (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\ejs\lib\ejs.js:274:36)
    at exports.renderFile [as engine] (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\express\lib\application.js:609:3)
    at ServerResponse.render (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\express\lib\response.js:1039:7)
    at res.render (C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\node_modules\express-ejs-layouts\lib\express-layouts.js:77:18)
    at C:\Users\Fifth\Documents\Programming\FishWatch\FishWatch\controllers\fishes.js:18:13"
